# Generated by Django 4.1.7 on 2023-06-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
